
package com.jie.test.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWebServiceImpl", targetNamespace = "http://webservice.test.jie.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWebServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWebService")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "HelloWebService", targetNamespace = "http://webservice.test.jie.com/", className = "com.jie.test.webservice.HelloWebService")
    @ResponseWrapper(localName = "HelloWebServiceResponse", targetNamespace = "http://webservice.test.jie.com/", className = "com.jie.test.webservice.HelloWebServiceResponse")
    @Action(input = "http://webservice.test.jie.com/HelloWebServiceImpl/HelloWebServiceRequest", output = "http://webservice.test.jie.com/HelloWebServiceImpl/HelloWebServiceResponse")
    public String helloWebService(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
