<?xml version="1.0" encoding="UTF-8"?>
<definitions
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsp="http://www.w3.org/ns/ws-policy" xmlns:wsp1_2="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:tns="http://webservice.test.jie.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://webservice.test.jie.com/"
	name="HelloWebServiceImplService">
	<types>
		<xsd:schema>
			<xsd:import namespace="http://webservice.test.jie.com/"
				schemaLocation="http://localhost:8088/HelloWebService/?xsd=1"></xsd:import>
		</xsd:schema>
	</types>
	<message name="HelloWebService">
		<part name="parameters" element="tns:HelloWebService"></part>
	</message>
	<message name="HelloWebServiceResponse">
		<part name="parameters" element="tns:HelloWebServiceResponse"></part>
	</message>
	<portType name="HelloWebServiceImpl">
		<operation name="HelloWebService">
			<input
				wsam:Action="http://webservice.test.jie.com/HelloWebServiceImpl/HelloWebServiceRequest"
				message="tns:HelloWebService"></input>
			<output
				wsam:Action="http://webservice.test.jie.com/HelloWebServiceImpl/HelloWebServiceResponse"
				message="tns:HelloWebServiceResponse"></output>
		</operation>
	</portType>
	<binding name="HelloWebServiceImplPortBinding" type="tns:HelloWebServiceImpl">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"
			style="document"></soap:binding>
		<operation name="HelloWebService">
			<soap:operation soapAction=""></soap:operation>
			<input>
				<soap:body use="literal"></soap:body>
			</input>
			<output>
				<soap:body use="literal"></soap:body>
			</output>
		</operation>
	</binding>
	<service name="HelloWebServiceImplService">
		<port name="HelloWebServiceImplPort" binding="tns:HelloWebServiceImplPortBinding">
			<soap:address location="http://localhost:8080/HelloWebService/"></soap:address>
		</port>
	</service>
</definitions>